# Development image
FROM php:8.3-apache

# Install system deps and mysqli extension
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    vim \
    libicu-dev \
    libzip-dev \
    && docker-php-ext-install \
       mysqli \
       pdo \
       pdo_mysql \
       intl \
       zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Install Xdebug for debugging
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Configure Xdebug (IDE key + remote debugging)
COPY ./devops/xdebug/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Set working dir
WORKDIR /var/www/html

# Copy composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install dependencies (with dev tools)
RUN composer install --no-interaction --no-progress

# Expose port 80
EXPOSE 80

# Set document root (Apache)
ENV APACHE_DOCUMENT_ROOT=/var/www/html

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
 && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Start Apache
CMD ["apache2-foreground"]
