version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: devops/Dockerfile.dev  # switch to Dockerfile for production
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: vacation_management_db
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacation_management_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
